"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from config import DjangoConfig, CeleryConfig, MariaConfig
import django_redis
import os

#* Validar configuraciones
DjangoConfig.validate()
CeleryConfig.validate()
MariaConfig.validate()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = DjangoConfig.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = DjangoConfig.DEBUG

ALLOWED_HOSTS = ['http://localhost:5173/']
#ALLOWED_HOSTS = DjangoConfig.ALLOWED_HOSTS

# ============================================================================
# INSTALLED_APPS
# ============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'TelemetriaDelancer',
]

# ============================================================================
# MIDDLEWARE
# ============================================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ============================================================================
# CONFIGURACIÓN DE REST FRAMEWORK
# ============================================================================
REST_FRAMEWORK = {
    #* Permisos por defecto para DjangoModelPermissionsOrAnonReadOnly
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}

# ============================================================================
# URLs
# ============================================================================
ROOT_URLCONF = 'backend.urls'

# ============================================================================
# WSGI APPLICATION
# ============================================================================
WSGI_APPLICATION = 'backend.wsgi.application'

# ============================================================================
# TEMPLATES
# ============================================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ============================================================================
# DATABASES
# ============================================================================
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SQLite
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# ============================================================================
# CONFIGURACIÓN DE BASE DE DATOS (MariaDB/MySQL)
# ============================================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': MariaConfig.Maria_NAME, 
        'USER': MariaConfig.Maria_USER,
        'PASSWORD': MariaConfig.Maria_PASSWORD,
        'HOST': MariaConfig.Maria_HOST,
        'PORT': MariaConfig.Maria_PORT,
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
        # Optimizaciones para mejor rendimiento con carga alta
        'CONN_MAX_AGE': 1000,  # Mantener conexiones vivas por 5 minutos (reducir overhead)
        'AUTOCOMMIT': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# CONFIGURACIÓN DE CACHE
# ============================================================================

# Configuración de cache usando Redis (mismo que Celery)
# Intenta usar django-redis, si no está disponible usa el backend nativo de Django
try:
    # Usar django-redis si está disponible (mejor rendimiento y funcionalidades)
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': CeleryConfig.CELERY_BROKER_URL,  # Usar la misma URL de Redis
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'telemetria',
            'TIMEOUT': 300,  # Tiempo de expiración por defecto: 5 minutos
            'VERSION': 1,
        }
    }
except ImportError:
    # Fallback al backend nativo de Django si django-redis no está instalado
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': CeleryConfig.CELERY_BROKER_URL,
            'KEY_PREFIX': 'telemetria',
            'TIMEOUT': 300,
            'VERSION': 1,
        }
    }

# Tiempos de cache específicos para diferentes tipos de datos (en segundos)
CACHE_TIMEOUT_SHORT = 60      # 1 minuto - para datos que cambian frecuentemente
CACHE_TIMEOUT_MEDIUM = 300    # 5 minutos - para datos que cambian ocasionalmente
CACHE_TIMEOUT_LONG = 3600     # 1 hora - para datos que cambian raramente
CACHE_TIMEOUT_ANALYTICS = 1800  # 30 minutos - para resultados de análisis

# ============================================================================
# CONFIGURACIÓN DE LOGGING
# ============================================================================

# Crear directorio de logs si no existe
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '[{asctime}] {levelname} [{name}] {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'unicode_safe': {
            '()': 'TelemetriaDelancer.utils.logging_handlers.UnicodeSafeFilter',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            '()': 'TelemetriaDelancer.utils.logging_handlers.SafeConsoleHandler',
            'formatter': 'detailed',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'detailed',
        },
        'panaccess_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'panaccess.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'detailed',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'errors.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'detailed',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'TelemetriaDelancer': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
            'filters': ['unicode_safe'],
        },
        'TelemetriaDelancer.server.panaccess_singleton': {
            'handlers': ['console', 'panaccess_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
            'filters': ['unicode_safe'],
        },
        'TelemetriaDelancer.utils.auth': {
            'handlers': ['console', 'panaccess_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
            'filters': ['unicode_safe'],
        },
        'TelemetriaDelancer.server.panaccess_client': {
            'handlers': ['console', 'panaccess_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
            'filters': ['unicode_safe'],
        },
        'TelemetriaDelancer.apps': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
            'filters': ['unicode_safe'],
        },
    },
}

# ============================================================================
# CONFIGURACIÓN DE CELERY
# ============================================================================

# Usar configuración desde config.py (variables de entorno)
CELERY_BROKER_URL = CeleryConfig.CELERY_BROKER_URL
CELERY_RESULT_BACKEND = CeleryConfig.CELERY_RESULT_BACKEND

# Serialización
CELERY_TASK_SERIALIZER = CeleryConfig.CELERY_TASK_SERIALIZER
CELERY_ACCEPT_CONTENT = CeleryConfig.CELERY_ACCEPT_CONTENT
CELERY_RESULT_SERIALIZER = CeleryConfig.CELERY_RESULT_SERIALIZER

# Timezone
CELERY_TIMEZONE = CeleryConfig.CELERY_TIMEZONE
CELERY_ENABLE_UTC = CeleryConfig.CELERY_ENABLE_UTC

# Configuración de workers
# Prefetch multiplier: None = sin límite, los workers toman tareas según necesidad
CELERY_WORKER_PREFETCH_MULTIPLIER = CeleryConfig.CELERY_WORKER_PREFETCH_MULTIPLIER
CELERY_TASK_ACKS_LATE = CeleryConfig.CELERY_TASK_ACKS_LATE

# Configuración de reintentos
CELERY_TASK_DEFAULT_RETRY_DELAY = CeleryConfig.CELERY_TASK_DEFAULT_RETRY_DELAY
CELERY_TASK_MAX_RETRIES = CeleryConfig.CELERY_TASK_MAX_RETRIES

# Configuración de tareas
CELERY_TASK_TRACK_STARTED = CeleryConfig.CELERY_TASK_TRACK_STARTED

# Sin límites de tiempo - las tareas duran lo que necesiten
# (No se configuran CELERY_TASK_TIME_LIMIT ni CELERY_TASK_SOFT_TIME_LIMIT)
